### ISSUE TITLE
Allow generic tickers

### ISSUE THREAD

**Issue by pmeier** [tkennon/ticker#1]
Would it be possible to make

https://github.com/tkennon/ticker/blob/4a945402cbfbd76c16bda2480f71dd2831068d50/ticker.go#L41

and subsequently

https://github.com/tkennon/ticker/blob/4a945402cbfbd76c16bda2480f71dd2831068d50/ticker.go#L16-L18

public? I want to implement a custom ticker and would rather not vendor the whole library.

**Comment by tkennon** [comment]
Yep, of course. I'll try and find some time this weekend.
